(define storage (or (read-storage 'guild) (list) ))

(define (add-peep) (if (write-storage 'guild (cons string-args storage)) "Peep added!" "Could not add Peep."))
(define (post-peep) (list-ref storage (random 0 (length storage))))
(define (debug) 
  (if (equal? string-args "debug")
    (make-attachment
      (string->bytes/utf-8 (string-join storage "\n"))
      "peeps.txt"
      'text/plain
    )
    (if (< (string-length string-args) 5) (post-peep) (add-peep))
  )
)
(define (reset)
  (if (equal? string-args "reset")
    (if (write-storage 'guild (list)) "Storage reset." "An error occurred when resetting storage")
    (debug)
  )
)
(define (remove) 
  (if (and (> (string-length string-args) 7) (equal? (substring string-args 0 6) "remove"))
    (if (write-storage 'guild (remove (substring string-args 7) storage)) "Peep removed... );" "Failed to remove peep.")
    (reset)
  )
)
(define (route)
  (if (equal? message-author "150753715727368193")
    (remove)
    (post-peep)
  )
)

(route)